language: r
sudo: false
cache: packages

matrix:
  include:
    - r: release
    - r: devel

env:
  global:
    - R_PKG="$(basename $TRAVIS_REPO_SLUG)"
    - secure: a1Gy+vPWuanEz0M2tIMEV6JSETmSzEX8x2hNLW2H98D5qDTVzxSBrG3IyyBEjvrfqm1zv/AUIYuLksIW6k+hCq9CTI7/hd+wAPygzvnj8ak0C0/3IWHmaOqYszIpDkyFgV30w3f5/8EcOc2f6VekynxS35EFRlEldXxpMyOHrFM=

repos:
  XRAN: https://xran.yihui.name

before_install:
  - "curl https://xran.yihui.org/.gitconfig -o ~/.gitconfig"

after_success:
  - "(curl https://xran.yihui.org/r-xran | bash)"
